name: test

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
